### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by junichi11** [junichi11/cakephp3-netbeans#11]
Unfortunately, this plugin depends on the build version of NetBeans #4 .

This problem will be resolved in the next stable version (probably NB8.1).

If there is not a nbm for your build version, please let me know. I'll create it for your version.
You can check it in Help > About . e.g. NetBeans 8.0.2 Patch 1 (Build 201411181905)

nbms are named like the following:
org-netbeans-modules-php-cake3-[plugin version number]-[dev]-[build version number of NetBeans].nbm
org-netbeans-modules-php-cake3-0.0.1-dev-201408251540.nbm

### another workaround

- Clone this repository
- Run create nbm

**Comment by curlyjason** [comment]
I am unable to install the plug-in in my build NetBeans IDE 8.0.2 (Build 201411181905).
It complains of:
- PHP Editor API
- PHP Executable API
- PHP Framework API
- PHP Module API
- Composer
- Web Common

I am using the proper build version from the downloads, but I am potentially not setting something up correctly in NetBeans

**Comment by junichi11** [comment]
Could you provide your error messages?

**Comment by curlyjason** [comment]
I can't select the text in the NetBeans dialog, but here's a screen grab of what it tells me when I attempt installation.

![screen shot 2015-05-20 at 7 09 41 pm](https://cloud.githubusercontent.com/assets/1307159/7740281/dce27832-ff23-11e4-8e49-1d37e54fd9d5.png)

To be clear:
1. Download the org-netbeans-modules-php-cake3-0.0.5-dev-201411181905.nbm plug-in
2. From NetBeans Tools/Plugins/Downloaded
3. Select Add Plugins...
4. Choose the file
5. Select and click Install
6. Error appears, with only the Cancel button available

**Comment by junichi11** [comment]
Thanks!
Probably, I guess your build version number is not 201411181905.

Could you try to check `Help > About` again?

e.g.
Product Version: NetBeans IDE 8.0.2 (Build 201408251540)
Java: 1.7.0_80; Java HotSpot(TM) Client VM 24.80-b11
Runtime: Java(TM) SE Runtime Environment 1.7.0_80-b15
System: Linux version 3.2.0-83-generic-pae running on i386; UTF-8

**Comment by curlyjason** [comment]
Here's my NetBeans About:

Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 1
Java: 1.8.0_31; Java HotSpot(TM) 64-Bit Server VM 25.31-b07
Runtime: Java(TM) SE Runtime Environment 1.8.0_31-b15
System: Mac OS X version 10.10.3 running on x86_64; UTF-8; en_US (nb)
User directory: /Users/jasont/Library/Application Support/NetBeans/8.0.1
Cache directory: /Users/jasont/Library/Caches/NetBeans/8.0.1

**Comment by junichi11** [comment]
Thanks!
How did you update the IDE?

It seems that you installed v8.0.1 at first.

Can you confirm your jar file ? :
(e.g. netbeans8/php/modules/org-netbeans-modules-php-api-framework.jar)
Please try to check `OpenIDE-Module-Implementation-Version` if you can look at MANIFEST.MF file in the jar file.

another idea...
Please try to re-install the IDE without using old version User/Cache directory if possible. But please note that all user settings are cleared.

**Comment by curlyjason** [comment]
The OpenIDE-Module-Implementation-Version was 201408251540
I deleted my full NetBeans install (after exporting some code templates) and reinstalled 8.0.2, without using the old settings.
I had to load the junit module, then cakephp3-netbeans installed fine.
Thanks for your help!

**Comment by junichi11** [comment]
> The OpenIDE-Module-Implementation-Version was 201408251540

Perhaps, you were able to use the org-netbeans-modules-php-cake3-0.0.5-dev-201408251540.nbm.

> I deleted my full NetBeans install (after exporting some code templates) and reinstalled 8.0.2, without using the old settings.
> I had to load the junit module, then cakephp3-netbeans installed fine.

:+1: 

Thanks!

**Comment by junichi11** [comment]
This problem is fixed in NetBeans 8.1.
Please try to test NetBeans 8.1 beta :)

**Comment by minhcanhdn** [comment]
Same error with netbean 8.0.2. How can i use this plugin with my netbeans version. I don't want to use beta version.

**Comment by junichi11** [comment]
@minhcanhdn What's your build version of NetBeans?

**Comment by minhcanhdn** [comment]
@junichi11 
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 2
Java: 1.8.0_51; Java HotSpot(TM) 64-Bit Server VM 25.51-b03
Runtime: Java(TM) SE Runtime Environment 1.8.0_51-b16
System: Windows 8 version 6.2 running on amd64; Cp1252; vi_VN (nb)
User directory: C:\Users\Brian\AppData\Roaming\NetBeans\8.0.2
Cache directory: C:\Users\Brian\AppData\Local\NetBeans\Cache\8.0.2

**Comment by junichi11** [comment]
@minhcanhdn Did you try using org-netbeans-modules-php-cake3-0.0.7-dev-201411181905.nbm?

**Comment by minhcanhdn** [comment]
@junichi11 
Yes, I used org-netbeans-modules-php-cake3-0.0.7-dev-201411181905.nbm version and result is same error.

**Comment by junichi11** [comment]
@minhcanhdn 
Could you provide a screenshot for your error message?
Then, please confirm the following : https://github.com/junichi11/cakephp3-netbeans/issues/11#issuecomment-104463328

**Comment by minhcanhdn** [comment]
![screenshot 2015-08-25 13 26 14](https://cloud.githubusercontent.com/assets/136077/9460101/f0ac70ca-4b2c-11e5-9cf7-483c63d10c4a.png)

**Comment by junichi11** [comment]
Thanks! Perhaps, You are using org-netbeans-modules-php-cake3-0.0.7-dev-201408251540.nbm. Please download org-netbeans-modules-php-cake3-0.0.7-dev-**201411181905**.nbm again.

If 201408251540.nbm already is shown in the install dialog when you install it, at first, please remove it.

**Comment by Krelyx** [comment]
Coul'd you create the nbm for netbeans 8.1RC2 please?

**Comment by junichi11** [comment]
@Krelyx 
Done. Could you try testing it?
https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.2.0

**Comment by Krelyx** [comment]
@junichi11 
Install is OK. Thanks

**Comment by junichi11** [comment]
@Krelyx 
Thanks :+1:

**Comment by Fluit** [comment]
Nope,
I'm getting the same errors:

![image](https://cloud.githubusercontent.com/assets/4445298/10581531/821916e0-7683-11e5-8161-0d3ad56e30ae.png)

version:
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 2
Java: 1.7.0_51; Java HotSpot(TM) Client VM 24.51-b03
Runtime: Java(TM) SE Runtime Environment 1.7.0_51-b13
System: Windows 7 version 6.1 running on x86; Cp1252; en_GB (nb)
User directory: C:\Users\HSM6900\AppData\Roaming\NetBeans\8.0.1
Cache directory: C:\Users\HSM6900\AppData\Local\NetBeans\Cache\8.0.1

thanks

**Comment by junichi11** [comment]
@Fluit 
Perhaps, you updated IDE from 8.0.1 to 8.0.2. Sorry, I don't provide nbm for 8.0.1.
So, could you please reinstall 8.0.2 or install 8.1-RC2?

Thanks.

**Comment by Fluit** [comment]
Yes, I did.
Plugin works fine after reinstalling 8.0.2.
Thanks for your help.

**Comment by junichi11** [comment]
You're welcome :)

**Comment by junichi11** [comment]
NetBeans 8.1 has been released! Just use the following : 
https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.2.1
