### ISSUE TITLE
Autocomplete $this-> in Layout .ctp files

### ISSUE THREAD

**Issue by adayth** [junichi11/cakephp3-netbeans#17]
I can't use autocomplete of $this-> in .ctp files inside Layout folder.

Maybe you can enable autocomplete in any .ctp file inside a cakephp3 project to avoid issues like this also with plugins and other folders.

**Comment by junichi11** [comment]
I'll fix it.

**Comment by junichi11** [comment]
I've fixed it. It's available on version 0.0.3 
https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.0.3
