### ISSUE TITLE
Code templates conflict with cakephp-netbeans plugin

### ISSUE THREAD

**Issue by adayth** [junichi11/cakephp3-netbeans#18]
When using autocomplete with cakephp3 and cakephp2 plugin installed and the project is of cakephp3, code templates of version 2 are shown.

**Comment by junichi11** [comment]
If you don't use them, please remove them manually.

**Comment by adayth** [comment]
But in standard PHP projects code templates doesn't appears and in cakephp3 yes. 
I think that for newbies will be confusing to have code templates for another version of the framework.
Don't know if can be avoided easily. Just my 50 cents.

**Comment by junichi11** [comment]
> But in standard PHP projects code templates doesn't appears and in cakephp3 yes.

No, code templates for cake appear in all php files.

> I think that for newbies will be confusing to have code templates for another version of the framework.
> Don't know if can be avoided easily.

Unfortunately, we can't switch(disable/enable) them in a specific file. i.e. If you add another code templates for PHP to your IDE, they also appear in your php files. e.g. If someone creates a code templates plugin for Laravel, then you install it, they appear in a php file even if it is a file for CakePHP.

I can change so as not to show them in a code completion list.(i.e. expand them only tab key) But there are some people to use them with code completion. So I want to avoid this.

**Comment by adayth** [comment]
First, sorry about the confusion. 

I was testing enabling / disabling cakephp2/3 plugins before posting this and because that I believed that worked only in cakephp projects.

I also was reviewing the code and noticed that code templates where in an xml file, so I deduce that are loaded magically by netbeans as part of plugin. Of course unload of all that templates by code could be a headache. I worked with nb-platform some years ago and the documentation was a mess.

Today, I tried to delete code templates, but after restarting netbeans, they appear again. If I've some free time I'll analyse if anything can be done to avoid this issue.

Thank you for the support and this great plugin. It saved a lot of development time with the autocomplete features.

**Comment by junichi11** [comment]
> First, sorry about the confusion.

Don't worry. Please just feel free to submit your issues. I'll look at them then, reply about them :)

> Today, I tried to delete code templates, but after restarting netbeans, they appear again. If I've some free time I'll analyse if anything can be done to avoid this issue.

It's a bug. But I've fixed ago in dev version. Sorry for inconvenience... 
Please try to use the dev version: https://github.com/junichi11/cakephp-netbeans/releases/tag/v0.12.3 (0.12.3.7)

**Comment by adayth** [comment]
Nice thank you!

2015-05-08 11:27 GMT+01:00 junichi11 <notifications@github.com>:

> First, sorry about the confusion.
>
> Don't worry. Please just feel free to submit your issues. I'll look at
> them then, reply about them :)
>
> Today, I tried to delete code templates, but after restarting netbeans,
> they appear again. If I've some free time I'll analyse if anything can be
> done to avoid this issue.
>
> It's a bug. But I've fixed ago in dev version. Sorry for inconvenience...
> Please try to use the dev version:
> https://github.com/junichi11/cakephp-netbeans/releases/tag/v0.12.3
> (0.12.3.7)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junichi11/cakephp3-netbeans/issues/18#issuecomment-100185729>
> .
>



-- 
Aday Talavera Hierro - Consultoría y desarrollo informático
Web: http://www.felfo.com  -  Email: aday.talavera@gmail.com
