### ISSUE TITLE
Code completion is slow

### ISSUE THREAD

**Issue by junichi11** [junichi11/cakephp3-netbeans#19]
Sometimes slow... So, I'm not sure how to reproduce it yet.

**Comment by Zwaen91** [comment]
I also detected that issue. It is really slow 90% of typing.

**Comment by junichi11** [comment]
@Zwaen91 Is it fast if you disable this plugin?

It seems to be slow when I typed `>` (e.g. $this->Html-`>`)

**Comment by Zwaen91** [comment]
For me every kind of autocompletion is slow. To get $this appearing takes over one second. After disabling it works like before - fast.

**Comment by junichi11** [comment]
You are right. It's fast after I disabled whole this plugin. But It's slow yet when I disabled only code completion feature. So I'll try to detect a problem.

Thanks.

**Comment by junichi11** [comment]
It seems that completion for parameters have a problem(s).

**Comment by junichi11** [comment]
I found the cause! So, I'll fix it soon.

**Comment by junichi11** [comment]
@Zwaen91 I've fixed it. It's available in version 0.0.5:
https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.0.5

Thanks.
