### ISSUE TITLE
Error when installing plugins

### ISSUE THREAD

**Issue by titamrtn** [junichi11/cakephp3-netbeans#28]
I've download "0.0.6 dev" and i got this error message ...
![capture](https://cloud.githubusercontent.com/assets/5078563/8567606/69ca7314-256f-11e5-85fe-c67d3b0ed097.PNG)

NOTE :
- I already look at issue #11 
- I have Netbeans 8.0.2 Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
- OpenIDE-Module-Implementation-Version: 201411181905

**Comment by junichi11** [comment]
Please try to use the org-netbeans-modules-php-cake3-0.0.6-dev-201408251540.nbm

**Comment by titamrtn** [comment]
I've try org-netbeans-modules-php-cake3-0.0.6-dev-201408251540.nbm and i got this error and when i try org-netbeans-modules-php-cake3-0.0.6-dev-201411181905.nbm it work great

**Comment by junichi11** [comment]
> But file directory is not lookin like in cake 2.x There is no shortcut to Model, Controller and view

Sorry, It has not implemented yet (#8). If I can make time, I'll do that. So, please wait a while...

Thanks.
