### ISSUE TITLE
Autocomplete for UrlHelper

### ISSUE THREAD

**Issue by adayth** [junichi11/cakephp3-netbeans#29]
#### Overview description
Autcomplete of UrlHelper isn't available.

#### Steps to reproduce
1. Go to any view file.
2. Write $this-> and Url isn't found. 

#### Expected results
Url helper should appear in autocomplete because is a core helper.

#### Version number of the plugin
0.0.5

#### Version information of NetBeans
8.0.2 (Build 201411181905)

**Comment by junichi11** [comment]
@adayth `Cake\View\View` is missing `@property` for UrlHelper. So, could you send a PR or submit an issue for it to cakephp/cakephp repository?

Thanks.

**Comment by adayth** [comment]
Issue submitted to cakephp repository cakephp/cakephp#7018

**Comment by junichi11** [comment]
@adayth Perfect! 

BTW, you used an issue template in this issue, it's so good :+1: 

Thanks.

**Comment by adayth** [comment]
No problem. I'm happy to collaborate with a tool that I use daily.

**Comment by junichi11** [comment]
Your PR is available in version 3.0.9 :) http://cakephp.org/changelogs/3.0.9
