### ISSUE TITLE
Create project with cakephp 3.0.9 fails on composer

### ISSUE THREAD

**Issue by PetervdPerk** [junichi11/cakephp3-netbeans#30]
It seems composer requires a confirmation on folder permissions
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
> App\Console\Installer::postInstall
Created `config/app.php` file
Set Folder Permissions ? (Default to Y) [Y,n]?
Since the Netbeans terminal doesnt accept input i cant complete project creation

**Comment by junichi11** [comment]
Thanks for reporting it.
I'll fix it. (add the --no-interaction option)

**Comment by junichi11** [comment]
@PetervdPerk What's your build version number of your NetBeans?

**Comment by PetervdPerk** [comment]
Thanks for your fast reaction my netbeans version is NetBeans IDE 8.0.2 (Build 201411181905).

**Comment by junichi11** [comment]
OK. I'll create a new nbm for testing soon. please wait a little. Sorry for inconvenience.

**Comment by junichi11** [comment]
@PetervdPerk 
Could you try to test it? : 
https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.0.6 (0.0.6.1-dev)

Thanks.

**Comment by PetervdPerk** [comment]
Thanks i've just tested 0.0.6.1 and it's working. Good work @junichi11 and thank you for this great Netbeans plugin.
