### ISSUE TITLE
New Project has error

### ISSUE THREAD

**Issue by masudafsar** [junichi11/cakephp3-netbeans#31]
when I create a new project ,Netbeans detect many errors in "vendor/cakephp/bake/src/Template/Bake" & "vendor/cakephp/migrations/src/Template/Bake/config" folders.

I guess because in PHP code section can't use Asp tags (<%= %>).

**Comment by junichi11** [comment]
Unfortunately, we can't do anything. It's not this plugin's problem.

**Comment by junichi11** [comment]
Probably, you can ignore them as a workaround. But some problems might occur.
