### ISSUE TITLE
Can use console from netbeans

### ISSUE THREAD

**Issue by titamrtn** [junichi11/cakephp3-netbeans#35]
Hi,

When i try to run cakephp command i got this error.

Note: I use 0.0.7 pre-release

![capture](https://cloud.githubusercontent.com/assets/5078563/9493661/f7fbbba0-4c09-11e5-97e8-b35def7707c4.PNG)

**Comment by junichi11** [comment]
Are there anything in IDE log?

**Comment by titamrtn** [comment]
[Fatal Error] nb-cake-commands-6594718312815091498.xml:2:6: La cible de l'instruction de traitement correspondant à "[xX][mM][lL]" n'est pas autorisée.
INFO [org.netbeans.modules.php.cake3.commands.Cake3Script]
org.xml.sax.SAXParseException; systemId: file:/C:/Users/LAWAPP~1/AppData/Local/Temp/nb-cake-commands-6594718312815091498.xml; lineNumber: 2; columnNumber: 6; La cible de l'instruction de traitement correspondant à "[xX][mM][lL]" n'est pas autorisée.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.netbeans.modules.php.cake3.commands.CakePHP3CommandXmlParser.parse(CakePHP3CommandXmlParser.java:75)
[catch] at org.netbeans.modules.php.cake3.commands.Cake3Script.getFrameworkCommandsInternalXml(Cake3Script.java:250)
	at org.netbeans.modules.php.cake3.commands.Cake3Script.getCommands(Cake3Script.java:217)
	at org.netbeans.modules.php.cake3.commands.CakePHP3FrameworkCommandSupport.getFrameworkCommandsInternal(CakePHP3FrameworkCommandSupport.java:98)
	at org.netbeans.modules.php.spi.framework.commands.FrameworkCommandSupport.refreshFrameworkCommands(FrameworkCommandSupport.java:150)
	at org.netbeans.modules.php.spi.framework.commands.FrameworkCommandSupport$1.run(FrameworkCommandSupport.java:181)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
CONFIG [null]: Parse error in file file:/C:/Users/LAWAPP~1/AppData/Local/Temp/nb-cake-commands-6594718312815091498.xml line 2 column 6 (PUBLIC null)
[Fatal Error] nb-cake-commands-6594718312815091498.xml:2:6: La cible de l'instruction de traitement correspondant à "[xX][mM][lL]" n'est pas autorisée.
INFO [org.netbeans.modules.php.cake3.commands.Cake3Script]
org.xml.sax.SAXParseException; systemId: file:/C:/Users/LAWAPP~1/AppData/Local/Temp/nb-cake-commands-6594718312815091498.xml; lineNumber: 2; columnNumber: 6; La cible de l'instruction de traitement correspondant à "[xX][mM][lL]" n'est pas autorisée.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.netbeans.modules.php.cake3.commands.CakePHP3CommandXmlParser.parse(CakePHP3CommandXmlParser.java:75)
[catch] at org.netbeans.modules.php.cake3.commands.Cake3Script.getFrameworkCommandsInternalXml(Cake3Script.java:250)
	at org.netbeans.modules.php.cake3.commands.Cake3Script.getCommands(Cake3Script.java:217)
	at org.netbeans.modules.php.cake3.commands.CakePHP3FrameworkCommandSupport.getFrameworkCommandsInternal(CakePHP3FrameworkCommandSupport.java:98)
	at org.netbeans.modules.php.spi.framework.commands.FrameworkCommandSupport.refreshFrameworkCommands(FrameworkCommandSupport.java:150)
	at org.netbeans.modules.php.spi.framework.commands.FrameworkCommandSupport$1.run(FrameworkCommandSupport.java:181)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
CONFIG [null]: Parse error in file file:/C:/Users/LAWAPP~1/AppData/Local/Temp/nb-cake-commands-6594718312815091498.xml line 2 column 6 (PUBLIC null)

**Comment by junichi11** [comment]
Thanks!
Can you look at  the xml file(nb-cake-commands-6594718312815091498.xml) and provide it?

**Comment by titamrtn** [comment]
I can't found the file.

**Comment by junichi11** [comment]
Perhaps, it is removed soon. If you keep opening the C:/Users/LAWAPP~1/AppData/Local/Temp directory, you may be able to find it. 

If you cannot find it, can you run `cake command_list --xml`?

**Comment by titamrtn** [comment]
When i run this command i got an xml : 

<?xml version="1.0"?>
<shells><shell name="bake" call_as="Bake.bake" provider="Bake" help="Bake.bake -
h"/><shell name="migrations" call_as="Migrations.migrations" provider="Migration
s" help="Migrations.migrations -h"/><shell name="i18n" call_as="i18n" provider="
CORE" help="i18n -h"/><shell name="orm_cache" call_as="orm_cache" provider="CORE
" help="orm_cache -h"/><shell name="plugin" call_as="plugin" provider="CORE" hel
p="plugin -h"/><shell name="server" call_as="server" provider="CORE" help="serve
r -h"/><shell name="console" call_as="console" provider="app" help="console -h"/
></shells>

**Comment by junichi11** [comment]
Thanks!
What does `La cible de l'instruction de traitement correspondant à "[xX][mM][lL]" n'est pas autorisée.` mean in English?

**Comment by junichi11** [comment]
@titamrtn Are your `bin\cake` or `cake.bat` files UTF-8 without BOM?

**Comment by junichi11** [comment]
There are something(empty line, it's bom?) before `<?xml `.

**Comment by titamrtn** [comment]
I'm using `bin\cake` and i got this : 
```
<?xml version="1.0"?>
<shells>
    <shell name="migrations" call_as="Migrations.migrations" provider="Migrations" help="Migrations.migrations -h"/>
    <shell name="i18n" call_as="i18n" provider="CORE" help="i18n -h"/>
    <shell name="orm_cache" call_as="orm_cache" provider="CORE" help="orm_cache -h"/>
    <shell name="plugin" call_as="plugin" provider="CORE" help="plugin -h"/>
    <shell name="server" call_as="server" provider="CORE" help="server -h"/>
    <shell name="console" call_as="console" provider="app" help="console -h"/>
</shells>
```

And when i use `cake.bat` : 
```
<?xml version="1.0"?>
<shells>
    <shell name="bake" call_as="Bake.bake" provider="Bake" help="Bake.bake -h"/>
    <shell name="migrations" call_as="Migrations.migrations" provider="Migrations" help="Migrations.migrations -h"/>
    <shell name="i18n" call_as="i18n" provider="CORE" help="i18n -h"/>
    <shell name="orm_cache" call_as="orm_cache" provider="CORE" help="orm_cache -h"/>
    <shell name="plugin" call_as="plugin" provider="CORE" help="plugin -h"/>
    <shell name="server" call_as="server" provider="CORE" help="server -h"/>
    <shell name="console" call_as="console" provider="app" help="console -h"/>
</shells>
```

**Comment by junichi11** [comment]
According to your screenshot, there is empty line before <?xml ?>. So, probably the XML parser throw an Exception.
I guess that your file encoding is `UTF-8 with BOM`. If so, you should use `UTF-8`(`UTF-8 without BOM`).  Can you confirm your file encoding?

**Comment by titamrtn** [comment]
Where i can change file encoding?

**Comment by junichi11** [comment]
Before that, you should check your file encoding. 

If you have a hex editor, open your files using it, then just try checking the beginning (3 bytes) of them.

If starts with `EF BB BF`, it is UTF-8 with BOM. Just try removing it.(How to remove: Just try searching it with Google)  Otherwise, this is not UTF-8 BOM's problem.

![utf-8-with-bom](https://cloud.githubusercontent.com/assets/738383/9848534/0288818a-5b1d-11e5-9f13-0bd9840ea0b5.png)

![utf-8-without-bom](https://cloud.githubusercontent.com/assets/738383/9848537/0907e582-5b1d-11e5-9637-df4db7f55971.png)

**Comment by junichi11** [comment]
@titamrtn I found the cause. It is the bat file problem. But I'll fix it. Instead of bat file, directly use cake.php file.

Thanks.

**Comment by junichi11** [comment]
Fixed. Could you try testing it if possible? 
https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.2.3

**Comment by junichi11** [comment]
Sorry, changes are missing.

**Comment by junichi11** [comment]
Fixed. https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.2.4
