### ISSUE TITLE
Setup of cakephp project in netbeans

### ISSUE THREAD

**Issue by ameydarlo** [junichi11/cakephp3-netbeans#36]
Hi,

I am very new to php as well as cakephp. I have installed cakephp via composer in the xampp htdocs folder.  I was able to successfully change database file and open index.php in web browser .
1. I am trying using netbeans to setup and work on cake php project. I have managed to install latest plugin provided by you. 
2. I did create php project and tried to enable framework. I do not understand cake php installed in xampp folder has a project name and as well as I create one in netbeans . 
3. When we enable framework , how exactly to set relative path. I do not understand that. 
Is it possible for you to please provide step by step to setup project in netbeans . Sorry , but I could not find exact setup procedure to my understanding on internet. 
Thanks in advance for your help.
![enabling-cakephp](https://cloud.githubusercontent.com/assets/14025122/9560343/d54001da-4e51-11e5-910b-57cba0651183.png)
![myphp-project](https://cloud.githubusercontent.com/assets/14025122/9560344/d542d4c8-4e51-11e5-8bb1-e22258c81e12.png)

**Comment by junichi11** [comment]
Hi, 
Your PhpProject1 is not cakephp3.
Where is your root directory of cakephp3 project in the xampp? /path/to/htdocs/cakephp3?

Please create a new PHP project using it.
New Project > PHP > PHP Application with Existing Source

**Comment by ameydarlo** [comment]
Hi,
Thank you for your quick resposne. 
1. I think i have only installed cakephp skeleton . that is an inside of app folder through composer. 
2. Should I create a netbeans projects first and then install cakephp skeleton in there ? 
3. Should I myself create app folder in  netbeans project and add these skeleton files to it ? 
Thanks again .

**Comment by junichi11** [comment]
> 1. I think i have only installed cakephp skeleton . that is an inside of app folder through composer. 

Please write your exact steps
.
> 2. Should I create a netbeans projects first and then install cakephp skeleton in there ? 
> 3. Should I myself create app folder in netbeans project and add these skeleton files to it ?

![nb-cakephp3-issue36](https://cloud.githubusercontent.com/assets/738383/9560442/4a586b5e-4e4f-11e5-928b-7c1db7f721d2.png)
No, if you have a cakephp project, as I wrote the above, please just a new PHP Project (New Project > PHP > PHP Application with Existing Source)

**Comment by ameydarlo** [comment]
Hi , 
I just ran the command 
composer create-project --prefer-dist cakephp/app [app_name] .
on the composer  by going into xampp folder 
As you said , I am able to create project through existing one , but still I cant get the app folder . 
Rest I was able to run the index.php . But now It gives errors 
![errors-project](https://cloud.githubusercontent.com/assets/14025122/9560508/d1d3e846-4e5a-11e5-91b2-0d96abe3663a.png)
Could you please guide me how exactly to install cakephp and which file ? 

Thank you once again.

**Comment by junichi11** [comment]
> but still I cant get the app folder

What does "app folder" mean?

> Rest I was able to run the index.php . But now It gives errors

What's the errors? 

> Could you please guide me how exactly to install cakephp and which file ?

Sorry, here is not proper place to tell how to use NetBeans... If your issue is not my plugin's problem, you should submit it to forums(CakePHP, NetBeans).
Perhaps, at first, you should learn how to use the NetBeans IDE [1].

[1] https://netbeans.org/kb/trails/php.html

**Comment by junichi11** [comment]
> Rest I was able to run the index.php . But now It gives errors

Perhaps, you don't set webroot in the project properties.
Please try setting it. Right-Click Project node > Properties > Sources > Web Root

**Comment by ameydarlo** [comment]
Hi , 
Thank you very much for your help . Yes , I could resolve the issue as you said above through setting web root.

**Comment by junichi11** [comment]
:+1:

**Comment by ameydarlo** [comment]
Hey , 
You said  , to set relative path 
Set relative paths from your Source Directory to Path settings . What does that exactly mean ? How to set relative path 
![relativepath](https://cloud.githubusercontent.com/assets/14025122/9560775/0e3f8c3a-4e6b-11e5-874e-7bd76df5929c.png)
Thanks for your help and time

**Comment by junichi11** [comment]
Namespace is not path. 

Source directory means Project properties > Sources > Source Folder
Root is base directory for "src" and "WWW Root".

Basically, set values of `config/app.php`.

```php 
    'App' => [
        'namespace' => 'App',
        'encoding' => 'UTF-8',
        'base' => false,
        'dir' => 'src',
        'webroot' => 'webroot',
        'wwwRoot' => WWW_ROOT,
        // 'baseUrl' => env('SCRIPT_NAME'),
        'fullBaseUrl' => false,
        'imageBaseUrl' => 'img/',
        'cssBaseUrl' => 'css/',
        'jsBaseUrl' => 'js/',
        'paths' => [
            'plugins' => [ROOT . DS . 'plugins' . DS],
            'templates' => [APP . 'Template' . DS],
            'locales' => [APP . 'Locale' . DS],
        ],
    ],
```

**Comment by ameydarlo** [comment]
Hi , 
Yup . Thank you very much . That made things working. 
Now I have parsing errors in the vendor folder . 
I am missing something to get those errors? 
How can I get rid of them ? 
Thank you.

**Comment by junichi11** [comment]
> Yup . Thank you very much . That made things working.

You are welcome :)

> Now I have parsing errors in the vendor folder . 
> I am missing something to get those errors? 
> How can I get rid of them ?

Unfortunately, It's not this plugin's problem. PHP editor parses source code and shows errors or warnings. So, the plugin cannot do anything. 
Please open the error files and confirm them by yourself.

Thanks.

**Comment by ameydarlo** [comment]
Hi , 
Yup. Thank you very much. Now understood what you mean to say. 
Thanks for all your help and time.
