### ISSUE TITLE
How to set up the project properties for a project on netbeans (enabling cakephp 3)

### ISSUE THREAD

**Issue by kayAbdulrazaq** [junichi11/cakephp3-netbeans#38]
I have been trying to enable cake php 3 support for my netbeans project but I am not sure what to enter in the paths required. What path settings should I enter for the root,  WWW ROOT, and .Cake?

Any suggestions, please and thank you.

**Comment by junichi11** [comment]
Please try looking at the following : 
- https://github.com/junichi11/cakephp3-netbeans#root
- https://github.com/junichi11/cakephp3-netbeans#the-others
- https://github.com/junichi11/cakephp3-netbeans#support-for-a-cake-file
- https://github.com/junichi11/cakephp3-netbeans/issues/36#issuecomment-135948193

Thanks.
