### ISSUE TITLE
Can't install due to missing dependencies? 

### ISSUE THREAD

**Issue by powerriegel** [junichi11/cakephp3-netbeans#40]
This happens when I follow your installation instructions on Ubuntu 14.04.0, Netbeans 8.0.2

Netbeans 8.0.2 is the current stable version. 

I can't find any of the missing plugins. 

Some plugins require plugin org.netbeans.api.progress.nb to be installed.
The plugin org.netbeans.api.progress.nb is requested in version 1.46.1.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin Progress API to be installed.
The plugin Progress API is requested in version >= 1.46.1 but only 1.38.1 was found.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin org.netbeans.api.templates to be installed.
The plugin org.netbeans.api.templates is requested in version 1.5.1.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin org.netbeans.modules.editor.document to be installed.
The plugin org.netbeans.modules.editor.document is requested in version 1.5.1.1.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin Editor Library 2 to be installed.
The plugin Editor Library 2 is requested in implementation version 44.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin org.netbeans.modules.extexecution.base to be installed.
The plugin org.netbeans.modules.extexecution.base is requested in version 1.1.1.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin org.netbeans.modules.parsing.indexing to be installed.
The plugin org.netbeans.modules.parsing.indexing is requested in version 9.6.1.1.1.8.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin PHP Editor API to be installed.
The plugin PHP Editor API is requested in version >= 0.24.1 but only 0.20.1 was found.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin PHP Executable API to be installed.
The plugin PHP Executable API is requested in version >= 0.30.1 but only 0.24.1 was found.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin PHP Framework API to be installed.
The plugin PHP Framework API is requested in version >= 0.24.1 but only 0.20.1 was found.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin PHP Module API to be installed.
The plugin PHP Module API is requested in version >= 2.53.1 but only 2.42.1 was found.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin Composer to be installed.
The plugin Composer is requested in version >= 0.29.1 but only 0.21.1 was found.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin Web Common to be installed.
The plugin Web Common is requested in implementation version 201510122201.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin File System API to be installed.
The plugin File System API is requested in version >= 9.8.1 but only 8.12.1 was found.  The following plugin is affected:       CakePHP3 Framework 
Some plugins require plugin org.openide.util.ui to be installed.
The plugin org.openide.util.ui is requested in version 9.3.1.  The following plugin is affected:       CakePHP3 Framework  Some plugins not installed to avoid potential installation problems.

**Comment by junichi11** [comment]
Did you read https://github.com/junichi11/cakephp3-netbeans/issues/11 ?
