### ISSUE TITLE
Trouble installing under NetBeans 8.1

### ISSUE THREAD

**Issue by curlyjason** [junichi11/cakephp3-netbeans#41]
#### Overview description
I am unable to install the plugin in NetBeans 8.1

#### Steps to reproduce
1. Downloaded the npm
2. Added to the Downloaded plug-ins and attempted to install

#### Actual results
NetBeans returns: Some plugins require plugin Web Common to be installed. The plugin Web Common is requested in implementation version 201510122201.

#### Expected results
The installed plugin

#### Version number of the plugin
0.2.0

#### Version information of NetBeans
NetBeans IDE 8.1 (Build 201510222201)

**Comment by junichi11** [comment]
Thanks for reporting it. 

I'll recreate a nbm in NetBeans8.1 later. Please wait a while.

**Comment by junichi11** [comment]
@curlyjason I've created a new nbm for NB8.1 stable.
https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.2.1 

Thanks!
