### ISSUE TITLE
Web Common needed

### ISSUE THREAD

**Issue by cameleonhelp** [junichi11/cakephp3-netbeans#43]
When i want to install the plugins in version 0.2.1 a message says that the extension Web Common is needed in version 201510222201 ?
System Info: 
  Product Version         = NetBeans IDE 8.1 (Build 201511021428) (#bb5d68d8a020)
  Operating System        = Mac OS X version 10.11.1 running on x86_64
  Java; VM; Vendor        = 1.8.0; Java HotSpot(TM) 64-Bit Server VM 25.0-b70; Oracle Corporation
  Runtime                 = Java(TM) SE Runtime Environment 1.8.0-b132
  Java Home               = /Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre
  System Locale; Encoding = fr_FR (nb); UTF-8

**Comment by junichi11** [comment]
Thanks for reporting it!

Fixed. Please try using the following:
https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.2.2
