### ISSUE TITLE
Run command is empty

### ISSUE THREAD

**Issue by cameleonhelp** [junichi11/cakephp3-netbeans#44]
When i tried tu execute "Run Command ..." the box is empty.
java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2056)
	at java.awt.Component.getLocationOnScreen(Component.java:2030)
	at sun.lwawt.macosx.CAccessibility$23.call(CAccessibility.java:395)
	at sun.lwawt.macosx.CAccessibility$23.call(CAccessibility.java:393)
	at sun.lwawt.macosx.LWCToolkit$CallableWrapper.run(LWCToolkit.java:534)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

This is the log IDE if it's help you. 
System Info: 
Product Version = NetBeans IDE 8.1 (Build 201511021428) (#bb5d68d8a020)
Operating System = Mac OS X version 10.11.1 running on x86_64
Java; VM; Vendor = 1.8.0; Java HotSpot(TM) 64-Bit Server VM 25.0-b70; Oracle Corporation
Runtime = Java(TM) SE Runtime Environment 1.8.0-b132
Java Home = /Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/jre
System Locale; Encoding = fr_FR (nb); UTF-8

**Comment by junichi11** [comment]
Could you run the following command via your terminal? `cake command_list --xml`

What's your version of CakePHP3?

Can you find the log related to this plugin? (The above log doesn't contain it.)

Thanks.

**Comment by cameleonhelp** [comment]
I use cakephp 3.1.5 the last version
The log return this : 
"/Volumes/web/cakephp315/bin/cake" "command_list"
PHP Fatal error:  You must enable the intl extension to use CakePHP. in /Volumes/web/cakephp315/config/bootstrap.php on line 38
PHP Fatal error:  You must enable the intl extension to use CakePHP. in /Volumes/web/cakephp315/config/bootstrap.php on line 38
Done.

But in my extension i tenable intl extension
<img width="615" alt="capture d ecran 2015-12-04 12 38 06" src="https://cloud.githubusercontent.com/assets/3072160/11588865/f02eccdc-9a83-11e5-87f0-76d944ffd1fb.png">
PHP is in 5.5.30

**Comment by junichi11** [comment]
> The log return this : 
> "/Volumes/web/cakephp315/bin/cake" "command_list"
> PHP Fatal error: You must enable the intl extension to use CakePHP. in /Volumes/web/cakephp315/config/bootstrap.php on line 38
> PHP Fatal error: You must enable the intl extension to use CakePHP. in /Volumes/web/cakephp315/config/bootstrap.php on line 38
> Done.

Is this the IDE log? or results of your terminal?

**Comment by cameleonhelp** [comment]
This is the IDE log for command_list i add the result for terminal at the end

**Comment by junichi11** [comment]
Did you try checking php.ini?

**Comment by junichi11** [comment]
Is your CakePHP application working fine? If no, perhaps, I guess that this is not plugin's problem.

**Comment by cameleonhelp** [comment]
CakePhp is working fine and my php.ni is correct with extension intl enable

**Comment by junichi11** [comment]
Thanks. Umm, PHP path of Options(Tools > Options > PHP) is correct?
But... something wrong because you cannot run the above command via your terminal. If you cannot do it, you cannot also run IDE.

**Comment by cameleonhelp** [comment]
He seems to be correct, it is the same i found in phpinfo

**Comment by junichi11** [comment]
Just try checking the following via terminal:
- `php -m | grep intl`
- `php -i | grep intl`

**Comment by junichi11** [comment]
Anyway, I think that it is not this plugin's problem because you cannot run the command via terminal at the moment... So, please try looking for the cause.

**Comment by cameleonhelp** [comment]
I tried on vitual machine under windows and a wamp server, i'll give you the result as soon

**Comment by cameleonhelp** [comment]
This is the log in IDE
Welcome to CakePHP v3.1.5 Console
---------------------------------------------------------------
App : src
Path: C:\wamp\www\cakephp315\src\
PHP : 5.5.12
---------------------------------------------------------------
Current Paths:

* app:  src
* root: C:\wamp\www\cakephp315
* core: C:\wamp\www\cakephp315\vendor\cakephp\cakephp

Available Shells:

[Bake] bake

[Migrations] migrations

[CORE] i18n, orm_cache, plugin, routes, server

[app] console

To run an app or core command, type `cake shell_name [args]`
To run a plugin command, type `cake Plugin.shell_name [args]`
To get help on a specific command, type `cake shell_name --help`


Done.

**Comment by cameleonhelp** [comment]
it is the same if i use the console

**Comment by junichi11** [comment]
It is the same as #35 . Then I found the cause of Windows case. It is bat file's problem. 
Please try remove `@echo.` (output an empty line) in the bin/cake.bat .

**Comment by junichi11** [comment]
Fixed windows problem. Unfortunately, I don't have Mac OS environment. So, I cannot reproduce your case.

**Comment by cameleonhelp** [comment]
Command appear but can't use them when i tried bake all this the result : 
Welcome to CakePHP v3.1.5 Console
---------------------------------------------------------------
App : src
Path: C:\wamp\www\cakephp315\src\
PHP : 5.5.12
---------------------------------------------------------------
The following commands can be used to generate skeleton code for your application.

Available bake commands:

- all
- behavior
- cell
- component
- controller
- fixture
- form
- helper
- mailer
- migration
- migration_snapshot
- model
- plugin
- shell
- shell_helper
- template
- test

By using `cake bake [name]` you can invoke a specific bake task.

Done.

**Comment by junichi11** [comment]
Sorry, there are missing. Please use the following:
https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.2.4

**Comment by cameleonhelp** [comment]
ok work for me under windows
for my mac i must found the good path, i think, use for synology NAS
