### ISSUE TITLE
Bake command is unable to take input

### ISSUE THREAD

**Issue by anujsharma9196** [junichi11/cakephp3-netbeans#46]
Bake command is running but unable to make choice. As soon as Bake command is executed from run command, it presents a list along with 
`By using 'cake bake [name]' you can invoke a specific bake task.`
`Done.`

ex: selecting bake All command and executing it gives 
`Bake All`
`---------------------------------------------------------------`
`Possible model names based on your database:`
`- admins`
`- client_address_types`
`- client_addresses`
`Run 'cake bake all [name]' to generate skeleton files.`
`- admins`
`- client_address_types`
`- client_addresses`
`Run 'cake bake all [name]' to generate skeleton files.`
`Done.`

and there is no input console to select option or run the command manually.

**Comment by junichi11** [comment]
Did you input a parameter in the dialog?
Probably, it is not a plugin's problem. Please try running the same command via your terminal.

Thanks.

**Comment by junichi11** [comment]
If you have something problems, please reopen it. Thanks.
