### ISSUE TITLE
What should be the value of ".cake"?

### ISSUE THREAD

**Issue by hebweb** [junichi11/cakephp3-netbeans#47]
It's really impossible to understand from the readme.

i'm using the latest netbean+plugin, with cake 2.7 (on a wamp [bitnami])
the cake core is located in the same hierarchy as the Apache.

![screenshot_3](https://cloud.githubusercontent.com/assets/301017/12913412/3dc42a64-cf27-11e5-9373-0d8267123e3e.png)

**Comment by Draniu** [comment]
this is plugin for cake 3.x

**Comment by junichi11** [comment]
@hebweb As @Draniu wrote, it is for cake2. Here is not a proper place for it. But just one thing. If you installed CakePHP via Composer, just try to set nothing to `CakePHP Root`. The error means not the `.cake` but the `cake.php` file. If you cannot resolve your issue, please submit it to [1].

[1] https://github.com/junichi11/cakephp-netbeans

Thanks.
