### ISSUE TITLE
Autocomplete for core helpers enabled by default #enhancement

### ISSUE THREAD

**Issue by adayth** [junichi11/cakephp3-netbeans#48]
If you create a new project, without adding helpers in controller / AppView (this last I'm not sure), core helpers are not autocompleted. I think that could be a good idea to autocomplete always core helpers by default, so newbies in the framework will get a more friendly experience.

**Comment by junichi11** [comment]
Could you write example code and steps?

It works in my environment.
![nb-cake3-issue48-1](https://cloud.githubusercontent.com/assets/738383/15652476/7833da54-26c1-11e6-8e87-591db32edc46.png)

![nb-cake3-issue48-2](https://cloud.githubusercontent.com/assets/738383/15652480/7ede2184-26c1-11e6-92bc-9386f9752b00.png)

**Comment by adayth** [comment]
I checked the plugin against 3.0, 3.1 and 3.2 and didn't found any issues.
Probably I forgot to enable cakephp3 in project properties before trying autocomplete.
Thank you for your answer and your time invested in this plugin.
