### ISSUE TITLE
VERY slow for template files

### ISSUE THREAD

**Issue by ootomaskooo** [junichi11/cakephp3-netbeans#49]
#### Overview description
When editing .ctp or .php files, the editor gets really slow. It doesn't happen with other file types (css, js...) and happens only after installing this plugin. The issue disappears during editing of other file types and/or after uninstalling the plugin.

#### Steps to reproduce
1. Open any .ctp file or .php file
2. Start typing anything

#### Actual results
Very slow response from IDE, causing about 500ms delay between a keystroke and an actual character being inserted.

#### Expected results
Normal performance.

#### Version number of the plugin
0.2.4

#### Version information of NetBeans
NetBeans IDE 8.1 (Build 201510222201)

**Comment by junichi11** [comment]
Can you try to use 0.3.0 once?
Then, can you provide your snapshot[1]?

[1] http://wiki.netbeans.org/FaqProfileMeNow

Thanks.

**Comment by ootomaskooo** [comment]
Seem that uninstalling and installing the version 0.3.0 fixed the issue, thank you!

**Comment by junichi11** [comment]
Great to hear. Thanks for your verification :)
