### ISSUE TITLE
Netbeans 8.2RC requires "Editor Library 2" in order to use this plugin

### ISSUE THREAD

**Issue by spectatorx1** [junichi11/cakephp3-netbeans#51]
I need this plugin to use as i need to create something with phpcake and my ide is netbeans. I have installed version 8.2RC (because of php7 syntax support) of netbeans and when i try to add cakephp3-netbeans plugin to my ide i get error message like this:
"Some plugins require plugin Editor Library 2 to be installed."
Details of this message point out to cake3php-netbeans plugin.

If needed this is exact version of my netbeans:
NetBeans IDE 8.2 RC (Build 201609140952)

Can it be fixed?

**Comment by junichi11** [comment]
Fixed. Thanks for reporting!

https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.4.0

**Comment by spectatorx1** [comment]
Wow, i'm impressed, thanks for quick response and instant fix. Just to confirm: plugin has installed without issues and works as it supposed to.

**Comment by AtraXaz** [comment]
> Some plugins require plugin Editor Library 2 to be installed.
> The plugin Editor Library 2 is requested in implementation version 56.  The following plugin is affected:       Netbeans Minimap 
> 
> 

Netbeans Version 11.0

Got this problem on Netbeans Minimap :D

**Comment by junichi11** [comment]
@AtraXaz Please report it to not this plugin but that plugin.

**Comment by mridah** [comment]
@AtraXaz  same here...were you able to resolve it ?
