### ISSUE TITLE
can't run cmd on linux

### ISSUE THREAD

**Issue by LifeOrYou** [junichi11/cakephp3-netbeans#53]
Hello,

Can't you check the line 150 - 155 in 'cakephp3-netbeans-0.4.0/src/org/netbeans/modules/php/cake3/commands/Cake3Script.java'.
In you if you can't set the correct SCRIPT_NAME for linux.

But, i think. i no have lot of time for check this.

**Comment by junichi11** [comment]
Could you provide more information(the version of CakePHP,  plugin, and, NetBeans, e.t.c.) with your exact steps?

Thanks.

**Comment by LifeOrYou** [comment]
On linux environnement: 
Php : 7.0.12
Netbeans: 8.2
Cakephp: 3.3.*
PluginCake for Netbeans : 0.4.0.

On Netbeans, in CakePhp project, when i want to run a command, any commands are display in commands window.
I test the default command "cake server" but don't work again.

best regards.

**Comment by junichi11** [comment]
I'm sorry to be late. Thank you for your information. Umm, I cannot reproduce it. Can you run the command("cake server") in your terminal?

Product Version: NetBeans IDE 8.2 (Build 201609300101) Patch 2
Java: 1.8.0_144; Java HotSpot(TM) 64-Bit Server VM 25.144-b01
Runtime: Java(TM) SE Runtime Environment 1.8.0_144-b01
System: Linux version 4.4.0-93-generic running on amd64; UTF-8; ja_JP (nb)

Plugin: 0.4.1

Thanks.

**Comment by LifeOrYou** [comment]
I'm sorry but i haven't the configuration at time and can't run the command for test.

**Comment by junichi11** [comment]
> i haven't the configuration at time

I'm not sure what it means. If I cannot get more information, unfortunately, I cannot do anything, sorry...

So if you find something, please let me know.

Thanks.
