### ISSUE TITLE
The plugin Editor Library 2 is requested in implementation version 55.

### ISSUE THREAD

**Issue by welemski** [junichi11/cakephp3-netbeans#56]
After updating Netbeans 8.2, the cakephp3 plugin v0.4.0 no longer works.

Error message below:

> Some plugins require plugin Editor Library 2 to be installed.
> 
> The plugin Editor Library 2 is requested in implementation version 55.  
> The following plugin is affected:       CakePHP3 Framework

[Screenshot](http://imgur.com/a/6nCbq)

Info:

> Product Version: NetBeans IDE 8.2 (Build 201609300101)

**Comment by junichi11** [comment]
Thanks for reporting!

Fixed.
https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.4.1

**Comment by welemski** [comment]
Hi @junichi11 Thanks!

**Comment by VarunAgw** [comment]
Bit late to the party, but I had similar issue yesterday after a fresh install. Allowing internet access to NetBeans fixed it. I wish there was a way to download dependencies offline.
