### ISSUE TITLE
The module Editor Library was requested in implementation version "23" but only "24"

### ISSUE THREAD

**Issue by djz3r0** [junichi11/cakephp3-netbeans#57]
Warning - could not install some modules: Editor Macros - The module Editor Library was requested in implementation version "23" but only "24" was found. IDE Platform - The module named org.netbeans.modules.editor.macros/0-1 was needed and not found. 16 further modules could not be installed due to the above problems.

**Comment by junichi11** [comment]
Can you write your versions of NetBeans and the plugin?

**Comment by djz3r0** [comment]
Product Version: NetBeans IDE 8.2 (Build 201705191307)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2

Plugin: 0.4.1

**Comment by junichi11** [comment]
> Product Version: NetBeans IDE 8.2 (Build 201705191307)

Umm, strange build version.
Where did you download it?
What is your language?

**Comment by djz3r0** [comment]
my IDE language is set to english.
I've downloaded the latest version yesterday from the netbeans page

**Comment by junichi11** [comment]
I see. I cannot get the Build 201705191307. So I cannot provide the nbm for it.

Please try using zip version if possible.
https://netbeans.org/downloads/zip.html

Or you can build the plugin by yourself.

**Comment by djz3r0** [comment]
I've downloaded the zip version  NetBeans IDE 8.2 (Build 201610071157)
But getting the same error. looks like the plugin installation is updating the module...

**Comment by junichi11** [comment]
Please try to do the following:
http://w.planetnetbeans.org/topic64759.html

**Comment by junichi11** [comment]
Or remove zip version. Then, Please try to build the plugin in your first version(Product Version: NetBeans IDE 8.2 (Build 201705191307)).

How to build: e.g. see https://github.com/madflow/flow-netbeans-markdown#installation 

```
 1. git clone git://github.com/junichi11/cakephp3-netbeans.git
 2. Open the folder with NetBeans (Open Project)
 3. (Configure Target Platform if needed)
 4. Choose "Create NBM" from the project menu
 5. Install the plugin with: Tools -> Plugins -> Downloaded
```

**Comment by djz3r0** [comment]
I've build my own NBM and its working. Great thanks alot

**Comment by junichi11** [comment]
You're welcome.
