### ISSUE TITLE
The menu option 'CakePHP3 -> Run Command' produces an error

### ISSUE THREAD

**Issue by luukau** [junichi11/cakephp3-netbeans#59]
Hi,

I am currently using CakePHP 3.5.4 on a project. The menu option 'CakePHP3 -> Run Command' produces the following error (copied from the Netbeans output window):

"/var/local/rnd/source/worker-template/bin/cake" "command_list"
Exception: Unknown command `cake command_list`. Run `cake --help` to get the list of valid commands. in [/var/local/rnd/source/worker-template/vendor/cakephp/cakephp/src/Console/CommandRunner.php, line 177]
Done.

When selecting the same option for a CakePHP 3.3.x project, the menu option works as expected. Using the cake CLI, it appears that the command "command_list --xml' is no longer supported in this newer version of cake (ie 3.5.4, possibly 3.5.x).

**Comment by junichi11** [comment]
Thanks for reporting it! I'll fix it later.

**Comment by junichi11** [comment]
I've confirmed that this occurs in version 3.5.0.

**Comment by junichi11** [comment]
It should be OK now. Please try to use 0.4.1.1-dev : https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.4.1

If there is no problem, I'll release it as version 0.4.2.

Thanks.

**Comment by luukau** [comment]
All good now. Thanks :)
