### ISSUE TITLE
Add more shortcut custom nodes 

### ISSUE THREAD

**Issue by macchaka** [junichi11/cakephp3-netbeans#61]
#8 is very useful feature.
I just hope to be added few shortcuts for more useful.
This is enough at custom node. Not default choice.

- Template
- Template/Element *
- Model/Table *
- Model/Entity *
- Shell

*If it is enable to overlaped path.

**Comment by junichi11** [comment]
Done. https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.5.1 

Thanks!
