### ISSUE TITLE
Feature Request: Add tab for Controller/Entity/Table/Template/config in left sidebar

### ISSUE THREAD

**Issue by VarunAgw** [junichi11/cakephp3-netbeans#63]
I work on medium sized CakePHP projects with dozens of controller, model,.. and vertical navigation from let say controller folder to template folder is very painful and slow.

What I generally do is drag and drop folders (controller, entity,..) into the editor and they are created as a tab in left sidebar. But it doesn't persist across session.

Ideally I want to do this in automated way with the plugin. I prefer to specify the name of folders I want as tab and whenever I load the project, tab should be created in left sidebar.

**Comment by junichi11** [comment]
Instead, please try to use custom nodes. (see: Tools > Options > PHP > Framework & Tools > CakePHP3)
![_110](https://user-images.githubusercontent.com/738383/38049625-aeea88c2-3303-11e8-9fe4-2421113e8965.png)
![_111](https://user-images.githubusercontent.com/738383/38049735-ee5f7ca6-3303-11e8-8997-a9c37e4c9e6f.png)

**Comment by VarunAgw** [comment]
Thanks. I know about it. But horizontal scrolling is so annoying

**Comment by junichi11** [comment]
Unfortunately, it is not this plugin's feature. It should be fixed in NetBeans itself. Please report your request to the NetBeans issue tracker.

Thanks for your understanding.

**Comment by VarunAgw** [comment]
Yeah definitely not your fault. I reported the issue earlier to them too. Thanks. It's quite a nice plugin actually and I like it :)
