### ISSUE TITLE
CakePHP 3.6 - Netbeans Plugin - Doesn't work

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [junichi11/cakephp3-netbeans#64]
I don't know what I did wrong.  
The version of my CakePHP is 3.6 and NetBeans IDE 8.2, plugin version 0.5.1  
The server doesn't start up.  
Can you help me?  

![project](https://user-images.githubusercontent.com/32627919/39705607-47b07210-51e5-11e8-837b-3e55ebb2a701.PNG)
![output](https://user-images.githubusercontent.com/32627919/39705611-4b7b84d4-51e5-11e8-9817-78a2cbfbbb0e.PNG)
![configurations](https://user-images.githubusercontent.com/32627919/39705616-4d6fa400-51e5-11e8-9065-23cf86344f09.PNG)

**Comment by acomerlatto** [comment]
Your PHP is not set to environment variables. So when you try to start the server it gives the error saying that it does not know the `php` command.

**Comment by danilobatistaqueiroz** [comment]
Thanks very much. Only added php's path in %PATH% variable and it worked!!
