### ISSUE TITLE
Apache Netbeans 10.0 compatibility

### ISSUE THREAD

**Issue by Montaire** [junichi11/cakephp3-netbeans#66]
#### Issue type

- [ ] bug
- [x] enhancement

#### Overview description
The plugin not working with the new Apache release.
The installer states Editor Library 2 v56 is required.

Probably the same as the #51 was.

**Comment by fdalex** [comment]
Would be great ... for Cakephp2.x version too ^^. This is the only thing I miss to go to netbeans 10.0

**Comment by junichi11** [comment]
Sorry, I'm late. I'll rebuild this plugin for NetBeans 10.
Thanks.

**Comment by junichi11** [comment]
Done.
https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.6.0
