### ISSUE TITLE
Upgrade for CakePHP 4.x

### ISSUE THREAD

**Issue by Fluit** [junichi11/cakephp3-netbeans#69]
#### Issue type

- [ ] bug
- [x] enhancement

#### Overview description
Suggesting to upgrade this plugin fot CakePHP 4.x.

**Comment by junichi11** [comment]
I haven't looked at CakePHP 4.x yet. If it can be supported by this plugin, I'll do it. Otherwise, maybe, I'll support it as a new plugin.

**Comment by junichi11** [comment]
**NOTE**: I wrote the above comment, but I can't promise anything.

**Comment by Fluit** [comment]
An upgrade of the templates could be an nice thing for a start.
May be, there are some other opportunities, but that i leave for your imagination;
So if you give me some instructions, i will/can help you out. (It's may be a chance to learn some java)

**Comment by lemuelmc** [comment]
Hi @junichi11 I've created PR: #72 : Partial support for CakePHP4 ( Added the autocomplete in templates with .php extensions )

**Comment by junichi11** [comment]
I've fixed. https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.8.0 
It would be nice if someone verify it (0.8.0.1-dev).

Thanks.

**Comment by Fluit** [comment]
Hi, @junichi11 
I gave it a try. These features work fine for me.

thx
Fluit

**Comment by junichi11** [comment]
@Fluit Great to hear. Thanks for your verification!
