### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by deb986** [junichi11/cakephp3-netbeans#70]
While try to add this plugin in NetBeans 12 it shows :

Installation completed unsuccessfully Click Finish to quit the NetBeans IDE installer and try to restart IDE.
The Plugin Installer found problem timeout of loading CakePHP3 Framework[org.netbeans.modules.php.cake3/0.7.0] while install the following plugins:
CakePHP3 Framework

Please help me on this.

**Comment by junichi11** [comment]
I'll rebuild the plugin later. So please wait a while. I can't promise when I do that, sorry.

**Comment by junichi11** [comment]
@deb986 I've rebuilt in NetBeans 12.0: https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.8.0
Please give it a try. Thanks!

**Comment by deb986** [comment]
Yes, it is working.
