### ISSUE TITLE
Run Command with CakePhp Version >= 4 will not show commands in popUp

### ISSUE THREAD

**Issue by nicokaiser79** [junichi11/cakephp3-netbeans#71]
#### Issue type
When you use CakePhp4, there is not possible to run commands. The command popup will be empty.
- [ ] bug
- [ ] enhancement

#### Overview description
When you use CakePhp4, there is not possible to run commands. The command popup will be empty.
#### Steps to reproduce

1. Install CakePhp 4
2. Go to your php project and try to run CakePhp3 command from context menu
3. The Run Command windows trigger the cake.php --help
4. The Result appear in the output window of netbeans

#### Actual results
The Result appear in the output window of netbeans

#### Expected results
the command list will be appear in the run command box

#### Your environment (NetBeans and plugin version, e.t.c.)
netbeans 12.1, cakephp3 0.8.0 

####Change
In File Cake3Script.java in Line 282 change the version handling:
from: if (version.getMajor() >= 3 && version.getMinor() >= 5)

to: if ((version.getMajor() >= 3 && version.getMinor() >= 5) || version.getMajor() > 3)

**Comment by junichi11** [comment]
CakePHP 4 is not supported in this plugin yet. If CakePHP 4 works with this plugin, I'll fix it later. Thanks.

**Comment by nicokaiser79** [comment]
Thanks for your answer. When plan you, to deploy a CakePHP4 plugin for netbeans? Thanks a lot.

**Comment by junichi11** [comment]
I've fixed. https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.8.0 
It would be nice if you verify it (0.8.0.1-dev).

Thanks.

**Comment by nicokaiser79** [comment]
it works very well!!! Thanks a lot.

**Comment by junichi11** [comment]
Great to hear :) Thanks for your verification!
