### ISSUE TITLE
add custom node

### ISSUE THREAD

**Issue by wate** [junichi11/cakephp3-netbeans#74]
#### Issue type

- [ ] bug
- [x] enhancement

#### Overview description

the directory generated by the following command does not support custom nodes, so please support it.

* `bin/cake bake cell`
* `bin/cake bake command`
* `bin/cake bake mailer`
* `bin/cake bake middleware`
* `bin/cake bake seed`
* `bin/cake bake plugin`
* `bin/cake bake shell_helper`
* `bin/cake bake task`
* `bin/cake bake fixture`
* `bin/cake bake test`

#### Expected results

the directories generated by commands that do not support custom nodes are as follows.

* `bin/cake bake cell` : `src/View/Cell/` and `src/Template/Cell/`
* `bin/cake bake command` : `src/Command/`
* `bin/cake bake mailer` : `src/Mailer/`
* `bin/cake bake middleware` : `src/Middleware/`
* `bin/cake bake seed` : `config/Seeds/`
* `bin/cake bake plugin` : `plugins/`
* `bin/cake bake shell_helper` :  `src/Shell/Helper/`
* `bin/cake bake task` :  `src/Shell/Task/`
* `bin/cake bake fixture` :  `tests/Fixture/`
* `bin/cake bake test` :  `tests/TestCase/`

**Comment by junichi11** [comment]
@wate CakePHP 3? CakePHP 4?

**Comment by wate** [comment]
@junichi11 

I'm using CakePHP 3 (3.9.8)

the items that can be generated by the bake command are as follows.

```
The following commands can be used to generate skeleton code for your application.

Available bake commands:

- all
- behavior
- cell
- command
- component
- controller
- fixture
- form
- helper
- mailer
- middleware
- migration
- migration_diff
- migration_snapshot
- model
- plugin
- seed
- shell
- shell_helper
- task
- template
- test
- twig_template
```

**Comment by junichi11** [comment]
> I'm using CakePHP 3 (3.9.8)

I see. Thank you :)

**Comment by junichi11** [comment]
@wate
I'm so sorry I'm late...
It would be nice if you can try using the dev version(0.9.0.1-dev): https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.9.0 
If there is something missing, please let me know.

I generated the plugin with NB12.0. 
If you are using another version, please let me know.

![netbeans-cakephp3-4-issue74-additional-custom-nodes](https://user-images.githubusercontent.com/738383/118768871-79185e00-b8ba-11eb-99fb-9a3f826a844f.png)

Thanks.

**Comment by junichi11** [comment]
Done:
- https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.9.1
- https://github.com/junichi11/cakephp3-netbeans/releases/tag/v0.10.1

If there is something missing, please feel free to let me know. Thanks.
